site_name: ExIFFI and EIF+ Documentation

theme:
  name: material 
  features:
  - navigation.tabs
  - navigation.sections
  - toc.integrate
  - navigation.top
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotation
  - content.code.copy
  language: en
  palette:
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline 
      name: Switch to dark mode
    primary: red
    accent: purple 
  - scheme: slate 
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode    
    primary: red
    accent: lime

  icon:
    repo: fontawesome/brands/github

  markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

repo_url: https://github.com/alessioarcudi/ExIFFI
repo_name: alessioarcudi/ExIFFI

plugins:
- mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
    default_handler: python
    handlers:
      python:
        options:
          show_source: true
- mkdocs-jupyter
# - git-committers:
#       repository: alessioarcudi/ExIFFI
#       branch: main
- search

nav:
  - Home: index.md
  - Dataset: datasets.md
  - Models: models.md
  - Utils: utils.md
  - Experiments: experiments.md
  - Plots: plots.md
  - Tutorial: tutorial.ipynb

